# Generated by Django 2.2.4 on 2019-09-27 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_vibg_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibg',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
