# Generated by Django 2.2.4 on 2019-09-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vibg_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibg',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
